# How to cache the things in github actions
name: Optiomisation checks - maven

on: workflow_dispatch
jobs:
  run-web-test:
    runs-on: ubuntu-latest

    steps:
        - name: pull the project in to runner
          uses: actions/checkout@v3

        - name: setup the java 
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11'
        
        - name: docker cache store
          uses: satackey/action-docker-layer-caching@v0.0.11
          continue-on-error: true

        - name: start selenoid server
          uses: n-ton4/selenoid-github-action@master
          id: start-selenoid
          continue-on-error: false
          with:
            version: 1.10.1
            args: -limit 10
            browsers: chrome
            last-versions: 1

        - name: Restore Maven cache
          uses: skjolber/maven-cache-github-action@v1
          continue-on-error: true
          with:
            step: restore
        
        - name: Run the testcases
          run: | 
            mvn clean test
        
        - name: Save Maven cache
          uses: skjolber/maven-cache-github-action@v1
          continue-on-error: true
          with:
            step: save
